name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  format-and-docs:
    name: Format and Documentation Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run format check
        run: cargo fmt --check

      - name: Run cargo-readme check
        run: cargo install cargo-readme && cargo readme > TMP_README.md && diff -b TMP_README.md README.md

  build-and-test:
    name: Build, Test, and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Run clippy
        run: cargo clippy --all-features -- -D warnings
